filter:
    excluded_paths:
        - 'js/vendor/*'
        - 'js/public/*'
        - 'js/tests/stubs/*'
        - 'templates/*'
        - 'l10n/*'
        - 'tests/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 1800
